//
// Code generated by grafana-app-sdk. DO NOT EDIT.
//

package v0alpha1

import (
	"github.com/grafana/grafana-app-sdk/resource"
)

// schema is unexported to prevent accidental overwrites
var (
	schemaExternalAlertmanagerSync = resource.NewSimpleSchema("admin.alerting.grafana.app", "v0alpha1", NewExternalAlertmanagerSync(), &ExternalAlertmanagerSyncList{}, resource.WithKind("ExternalAlertmanagerSync"),
		resource.WithPlural("externalalertmanagersyncs"), resource.WithScope(resource.NamespacedScope))
	kindExternalAlertmanagerSync = resource.Kind{
		Schema: schemaExternalAlertmanagerSync,
		Codecs: map[resource.KindEncoding]resource.Codec{
			resource.KindEncodingJSON: &ExternalAlertmanagerSyncJSONCodec{},
		},
	}
)

// Kind returns a resource.Kind for this Schema with a JSON codec
func ExternalAlertmanagerSyncKind() resource.Kind {
	return kindExternalAlertmanagerSync
}

// Schema returns a resource.SimpleSchema representation of ExternalAlertmanagerSync
func ExternalAlertmanagerSyncSchema() *resource.SimpleSchema {
	return schemaExternalAlertmanagerSync
}

// Interface compliance checks
var _ resource.Schema = kindExternalAlertmanagerSync
